baseURL = "http://localhost:49159/"            # Hosting location.
languageCode = "en-us"                         # Locale
tagline = "Data Scientist"                     # Name of the website
theme = "ananke"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number

[author]                                       # Information about the website author
email = "tom.andrew.wilson@gmail.com"
name = "Thomas Wilson"
location = "Pennsylvania"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
