title: Wilsonify
description: "Dream of Wilsonification"
tagline: "What you are about to experience are just my thoughts--right or wrong--just what I was feeling at the time"
theme: jekyll-theme-tactile
gems: ['jekyll-github-metadata']
